-- Drop all remaining RLS policies
DROP POLICY IF EXISTS "Workspace members can view activity log" ON public.activity_log;
DROP POLICY IF EXISTS "Users can view their own AI chat messages" ON public.ai_chat_messages;
DROP POLICY IF EXISTS "Users can view their own AI chat threads" ON public.ai_chat_threads;
DROP POLICY IF EXISTS "Authenticated users can access all categories" ON public.detail_library_categories;
DROP POLICY IF EXISTS "Authenticated users can access all files" ON public.detail_library_files;
DROP POLICY IF EXISTS "Authenticated users can access all items" ON public.detail_library_items;
DROP POLICY IF EXISTS "Authenticated users can access all subfolders" ON public.detail_library_subfolders;
DROP POLICY IF EXISTS "Workspace members can create drawing pages" ON public.drawing_pages;
DROP POLICY IF EXISTS "Workspace members can update drawing pages" ON public.drawing_pages;
DROP POLICY IF EXISTS "Workspace members can view drawing pages" ON public.drawing_pages;
DROP POLICY IF EXISTS "Workspace members can create drawing scales" ON public.drawing_scales;
DROP POLICY IF EXISTS "Workspace members can update drawing scales" ON public.drawing_scales;
DROP POLICY IF EXISTS "Workspace members can view drawing scales" ON public.drawing_scales;
DROP POLICY IF EXISTS "Workspace members can create drawings" ON public.drawings;
DROP POLICY IF EXISTS "Workspace members can update drawings" ON public.drawings;
DROP POLICY IF EXISTS "Workspace members can view drawings" ON public.drawings;
DROP POLICY IF EXISTS "Workspace members can view file annotations" ON public.file_annotations;
DROP POLICY IF EXISTS "Workspace members can view files" ON public.files;
DROP POLICY IF EXISTS "Workspace members can view folders" ON public.folders;
DROP POLICY IF EXISTS "Workspace members can view invoice line items" ON public.invoice_line_items;
DROP POLICY IF EXISTS "Workspace members can view invoices" ON public.invoices;
DROP POLICY IF EXISTS "Workspace members can view links" ON public.links;
DROP POLICY IF EXISTS "Workspace members can view notes" ON public.notes;
DROP POLICY IF EXISTS "Users can view their own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Workspace members can view project chat messages" ON public.project_chat_messages;
DROP POLICY IF EXISTS "Workspace members can create project members" ON public.project_members;
DROP POLICY IF EXISTS "Workspace members can update project members" ON public.project_members;
DROP POLICY IF EXISTS "Workspace members can view project members" ON public.project_members;
DROP POLICY IF EXISTS "Workspace members can create projects" ON public.projects;
DROP POLICY IF EXISTS "Workspace members can update projects" ON public.projects;
DROP POLICY IF EXISTS "Workspace members can view projects" ON public.projects;
DROP POLICY IF EXISTS "Workspace members can view tasks" ON public.tasks;
DROP POLICY IF EXISTS "Workspace members can view time entries" ON public.time_entries;
DROP POLICY IF EXISTS "Users can insert their own preferences" ON public.user_preferences;
DROP POLICY IF EXISTS "Users can update their own preferences" ON public.user_preferences;
DROP POLICY IF EXISTS "Users can view their own preferences" ON public.user_preferences;
DROP POLICY IF EXISTS "Users can view their own role" ON public.user_roles;
DROP POLICY IF EXISTS "Authenticated users can view users" ON public.users;
DROP POLICY IF EXISTS "Users can update their own profile" ON public.users;
DROP POLICY IF EXISTS "Users can delete their own workspace chat messages" ON public.workspace_chat_messages;
DROP POLICY IF EXISTS "Users can update their own workspace chat messages" ON public.workspace_chat_messages;
DROP POLICY IF EXISTS "Workspace members can create workspace chat messages" ON public.workspace_chat_messages;
DROP POLICY IF EXISTS "Workspace members can view workspace chat messages" ON public.workspace_chat_messages;
DROP POLICY IF EXISTS "Members can view workspace membership" ON public.workspace_members;
DROP POLICY IF EXISTS "Members can view workspace settings" ON public.workspace_settings;
DROP POLICY IF EXISTS "Members can view their workspaces" ON public.workspaces;